working on the artifact for ios

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -138,113 +138,114 @@ jobs:
 
 
   analyze3:
-    name: Analyze (${{ matrix.language }})
-    runs-on: ${{ (matrix.language == 'swift' && 'macos-15') || 'ubuntu-latest' }}
-    permissions:
-      # required for all workflows
-      security-events: write
+    #    name: Analyze (${{ matrix.language }})
+    #    runs-on: ${{ (matrix.language == 'swift' && 'macos-15') || 'ubuntu-latest' }}
+    #    permissions:
+    #      # required for all workflows
+    #      security-events: write
+    #
+    #      # required to fetch internal or private CodeQL packs
+    #      packages: read
+    #
+    #      # only required for workflows in private repositories
+    #      actions: read
+    #      contents: read
+    #
+    #    strategy:
+    #      fail-fast: false
+    #      matrix:
+    #        include:
+    #          - language: swift
+    #            build-mode: autobuild
 
-      # required to fetch internal or private CodeQL packs
-      packages: read
-
-      # only required for workflows in private repositories
-      actions: read
-      contents: read
-
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - language: swift
-            build-mode: autobuild
-  build-ios:
+    name: build iOS
     runs-on: macos-14
     env:
       TURBO_CACHE_DIR: .turbo/ios
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+      steps:
+        - name: Checkout
+          uses: actions/checkout@v3
 
-      - name: Setup
-        uses: ./.github/actions/setup
+        - name: Setup
+          uses: ./.github/actions/setup
 
-      - name: Cache turborepo for iOS
-        uses: actions/cache@v3
-        with:
-          path: ${{ env.TURBO_CACHE_DIR }}
-          key: ${{ runner.os }}-turborepo-ios-${{ hashFiles('yarn.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-turborepo-ios-
+        - name: Cache turborepo for iOS
+          uses: actions/cache@v3
+          with:
+            path: ${{ env.TURBO_CACHE_DIR }}
+            key: ${{ runner.os }}-turborepo-ios-${{ hashFiles('yarn.lock') }}
+            restore-keys: |
+              ${{ runner.os }}-turborepo-ios-
 
-      - name: Check turborepo cache for iOS
-        run: |
-          TURBO_CACHE_STATUS=$(node -p "($(yarn turbo run build:ios --cache-dir="${{ env.TURBO_CACHE_DIR }}" --dry=json)).tasks.find(t => t.task === 'build:ios').cache.status")
+        - name: Check turborepo cache for iOS
+          run: |
+            TURBO_CACHE_STATUS=$(node -p "($(yarn turbo run build:ios --cache-dir="${{ env.TURBO_CACHE_DIR }}" --dry=json)).tasks.find(t => t.task === 'build:ios').cache.status")
 
-          if [[ $TURBO_CACHE_STATUS == "HIT" ]]; then
-            echo "turbo_cache_hit=1" >> $GITHUB_ENV
-          fi
+            if [[ $TURBO_CACHE_STATUS == "HIT" ]]; then
+              echo "turbo_cache_hit=1" >> $GITHUB_ENV
+            fi
 
-      - name: Cache cocoapods
-        if: env.turbo_cache_hit != 1
-        id: cocoapods-cache
-        uses: actions/cache@v3
-        with:
-          path: |
-            **/ios/Pods
-          key: ${{ runner.os }}-cocoapods-${{ hashFiles('example/ios/Podfile.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-cocoapods-
+        - name: Cache cocoapods
+          if: env.turbo_cache_hit != 1
+          id: cocoapods-cache
+          uses: actions/cache@v3
+          with:
+            path: |
+              **/ios/Pods
+            key: ${{ runner.os }}-cocoapods-${{ hashFiles('example/ios/Podfile.lock') }}
+            restore-keys: |
+              ${{ runner.os }}-cocoapods-
 
-      - name: Install cocoapods
-        if: env.turbo_cache_hit != 1 && steps.cocoapods-cache.outputs.cache-hit != 'true'
-        run: |
-          cd example/ios
-          pod install
-        env:
-          NO_FLIPPER: 1
+        - name: Install cocoapods
+          if: env.turbo_cache_hit != 1 && steps.cocoapods-cache.outputs.cache-hit != 'true'
+          run: |
+            cd example/ios
+            pod install
+          env:
+            NO_FLIPPER: 1
 
-      - name: Build example for iOS
-        run: |
-          yarn turbo run build:ios --cache-dir="${{ env.TURBO_CACHE_DIR }}"
-          echo "${{ env.TURBO_CACHE_DIR }}"
+        - name: Build example for iOS
+          run: |
+            yarn turbo run build:ios --cache-dir="${{ env.TURBO_CACHE_DIR }}"
+            echo "${{ env.TURBO_CACHE_DIR }}"
 
 
-        #                -   name: 'Upload Artifact'
-        #                    uses: actions/upload-artifact@v4
-        #                    with:
-        #                        name: ios-artifact
-        #                        path:
+          #                -   name: 'Upload Artifact'
+          #                    uses: actions/upload-artifact@v4
+          #                    with:
+          #                        name: ios-artifact
+          #                        path:
 
 
         # Add any setup steps before running the `github/codeql-action/init` action.
-      # This includes steps like installing compilers or runtimes (`actions/setup-node`
-      # or others). This is typically only required for manual builds.
-      # - name: Setup runtime (example)
-      #   uses: actions/setup-example@v1
+        # This includes steps like installing compilers or runtimes (`actions/setup-node`
+        # or others). This is typically only required for manual builds.
+        # - name: Setup runtime (example)
+        #   uses: actions/setup-example@v1
 
-      # Initializes the CodeQL tools for scanning.
-      - name: Initialize CodeQL
-        uses: github/codeql-action/init@v3
-        with:
-          languages: ${{ matrix.language }}
-          build-mode: ${{ matrix.build-mode }}
-          # If you wish to specify custom queries, you can do so here or in a config file.
-          # By default, queries listed here will override any specified in a config file.
-          # Prefix the list here with "+" to use these queries and those in the config file.
+        # Initializes the CodeQL tools for scanning.
+        - name: Initialize CodeQL
+          uses: github/codeql-action/init@v3
+          with:
+            languages: ${{ matrix.language }}
+            build-mode: ${{ matrix.build-mode }}
+            # If you wish to specify custom queries, you can do so here or in a config file.
+            # By default, queries listed here will override any specified in a config file.
+            # Prefix the list here with "+" to use these queries and those in the config file.
 
-          # For more details on CodeQL's query packs, refer to: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
-          queries: ${{ matrix.language && 'security-extended, security-and-quality' }}
+            # For more details on CodeQL's query packs, refer to: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
+            queries: ${{ matrix.language && 'security-extended, security-and-quality' }}
 
-      - if: matrix.build-mode == 'manual'
-        shell: bash
-        run: |
-          echo 'If you are using a "manual" build mode for one or more of the' \
-            'languages you are analyzing, replace this with the commands to build' \
-            'your code, for example:'
-          echo '  make bootstrap'
-          echo '  make release'
-          exit 1
-      - name: Perform CodeQL Analysis
-        uses: github/codeql-action/analyze@v3
-        with:
-          category: "/language:${{matrix.language}}"
+        - if: matrix.build-mode == 'manual'
+          shell: bash
+          run: |
+            echo 'If you are using a "manual" build mode for one or more of the' \
+              'languages you are analyzing, replace this with the commands to build' \
+              'your code, for example:'
+            echo '  make bootstrap'
+            echo '  make release'
+            exit 1
+        - name: Perform CodeQL Analysis
+          uses: github/codeql-action/analyze@v3
+          with:
+            category: "/language:${{matrix.language}}"
